/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz1;

import javax.swing.JOptionPane;

/**
 *
 * @author JUAN DAVID
 */
public class interfaz2 extends javax.swing.JFrame {

    /**
     * Creates new form interfaz2
     */
    public interfaz2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        CoD = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        ark = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        over = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        wow = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lol = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        control = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        fondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(2, 2, 2));

        CoD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CoD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/call_of_duty-removebg-preview.png"))); // NOI18N
        CoD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CoD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CoDMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CoD, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CoD, javax.swing.GroupLayout.PREFERRED_SIZE, 180, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 240, 180));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        ark.setBackground(new java.awt.Color(40, 0, 0));
        ark.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ark-removebg-preview.png"))); // NOI18N
        ark.setToolTipText("");
        ark.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ark.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ark, javax.swing.GroupLayout.PREFERRED_SIZE, 240, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addComponent(ark, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 240, 180));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        over.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        over.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/over2-removebg-preview.png"))); // NOI18N
        over.setText("jLabel5");
        over.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        over.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                overMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(over, javax.swing.GroupLayout.PREFERRED_SIZE, 240, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(over, javax.swing.GroupLayout.PREFERRED_SIZE, 180, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 240, 180));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        wow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wow-removebg-preview.png"))); // NOI18N
        wow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        wow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wowMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(wow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(wow, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 240, 180));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        lol.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lol-removebg-preview.png"))); // NOI18N
        lol.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lolMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lolMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lol, javax.swing.GroupLayout.PREFERRED_SIZE, 241, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lol, javax.swing.GroupLayout.PREFERRED_SIZE, 182, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 240, 180));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 240, 150));

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jButton1.setText("INICIO");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 190, 40));

        control.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        control.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/control.png"))); // NOI18N
        control.setText("jLabel1");
        getContentPane().add(control, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 190, 210));

        jPanel7.setBackground(new java.awt.Color(153, 0, 0));

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Selecciona tu juego ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 500, 40));

        fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo 2.jpg"))); // NOI18N
        getContentPane().add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        main n = new main();
        n.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CoDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CoDMouseClicked
        JOptionPane.showMessageDialog( CoD, "Bienvenido a la Call Of Duty,\n iniciando...");
    }//GEN-LAST:event_CoDMouseClicked

    private void lolMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lolMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lolMouseEntered

    private void lolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lolMouseClicked
       JOptionPane.showMessageDialog( lol, "Bienvenido a la grieta del invocador,\n iniciando...");
    }//GEN-LAST:event_lolMouseClicked

    private void wowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wowMouseClicked
     JOptionPane.showMessageDialog( wow, "Bienvenido a la wow, ¿listo para explorar las mazmorras?,\n iniciando...");
    }//GEN-LAST:event_wowMouseClicked

    private void arkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arkMouseClicked
      JOptionPane.showMessageDialog( ark, "¿estas listo para una aventura con dinosaurios?,\n iniciando...");
    }//GEN-LAST:event_arkMouseClicked

    private void overMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_overMouseClicked
      JOptionPane.showMessageDialog( over, "Estas listo para manquear un rato, ¡malito!,\n iniciando...");
    }//GEN-LAST:event_overMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CoD;
    private javax.swing.JLabel ark;
    private javax.swing.JLabel control;
    private javax.swing.JLabel fondo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lol;
    private javax.swing.JLabel over;
    private javax.swing.JLabel wow;
    // End of variables declaration//GEN-END:variables
}
